name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APPLICATION_PORT: 80
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
        
      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        
      - name: Clean up old container
        run: |
          docker stop ${{ github.event.repository.name }} || true
          docker rm ${{ github.event.repository.name }}-old || true
          docker container rename ${{ github.event.repository.name }} ${{ github.event.repository.name }}-old || true
        continue-on-error: true
        
      - name: Deploy container
        run: docker run -d -p ${{ env.APPLICATION_PORT }}:8080 --name ${{ github.event.repository.name }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        
      - name: Clean up Docker images
        run: docker image prune -a -f